name: bibinto
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

#Localization
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

#Navigation
  auto_route: ^7.8.3

#UI
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  shimmer: ^3.0.0

#Image
  image_picker: ^1.0.7
  photo_manager: ^3.0.0
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.6

#GraphQL
  graphql_flutter: ^5.1.2

#Utils
  equatable: ^2.0.5

#HTTP
  http: ^1.2.0

  dio: ^5.4.2+1
  mime: ^1.0.5

#BLoC
  flutter_bloc: ^8.1.4
  stream_bloc: ^0.5.3
  bloc: ^8.1.3

#Validate
  email_validator: ^2.1.17

#Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#Code generation
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoForApp.jpg"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Golos Text
      fonts:
        - asset: assets/fonts/GolosText/GolosText-Regular.ttf
          weight: 400
        - asset: assets/fonts/GolosText/GolosText-Medium.ttf
          weight: 500
        - asset: assets/fonts/GolosText/GolosText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GolosText/GolosText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GolosText/GolosText-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/GolosText/GolosText-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
  class_name: Localized
  main_locale: ru
  arb_dir: assets/l10n
  output_dir: lib/src/common/localization
  use_deffered_loading: false

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  
